# Generated by Django 4.1.7 on 2023-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jd',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='skills',
        ),
    ]
